baseURL = "https://strandboden.netlify.app"
title = "Prés-de-la-Rive"

languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

cleanDestinationDir = true
disableFastRender = true
removePathAccents = true

disableKinds = [ "taxonomy", "term", "robotsTXT", "RSS", "sitemap", "404"]

[markup.goldmark.renderer]
unsafe = true

[minify]
minifyOutput = true

# Configuration du français 
[languages.fr]
contentDir = "content/fr"
languageName = "Français"
weight = 10

title = "Spot in Bienne"
footer = "Un projet de la [Ville de Bienne](https://www.biel-bienne.ch/) et [SPORTIWORLD](https://www.sportiworld.com/)."
annonce = """Cette page est présente pour des raisons techniques.

Merci de continuer la navigation jusqu'à trouver une page sans cette mention."""

# Configuration de l'allemand
[languages.de]
contentDir = "content/de"
languageName = "Deutsch"
weight = 20

title = "Spot in Biel"
footer = "Ein Projekt der [Stadt Biel](https://www.biel-bienne.ch/) und [SPORTIWORLD](https://www.sportiworld.com/)-"
annonce ="""Diese Seite ist aus technischen Gründen vorhanden.

Bitte setzen Sie die Navigation fort, bis Sie eine Seite ohne diesen Hinweis finden."""